In [3]:
# Numpy Library
#Reading file
with open('untitled.txt') as practiceFile: #with keyword: jb file pori read hujati ha tou ye keyword close krdeta ha file ko
    contents = practiceFile.read()
    print(contents)

123
456
789





In [4]:
with open('untitled.txt') as practiceFile: 
    contents = practiceFile.read()
    print(contents.rstrip()) #rstrip() method spaces aur empty space ko neglect krdeta ha

123
456
789


In [6]:
#Ab folder k ander kch files hou aur us file se data get hou
with open('Untitled Folder/untitled2.txt') as practiceFile: 
    contents = practiceFile.read()
    print(contents.rstrip()) 

Marium
Hamza
Asad
Hina
Arif


In [7]:
filePath = 'Untitled Folder/untitled2.txt'
with open(filePath) as practiceFile: 
    contents = practiceFile.read()
    print(contents.rstrip()) 

Marium
Hamza
Asad
Hina
Arif


In [10]:
filePath = 'untitled.txt'

with open(filePath) as practiceFile:
    contents = practiceFile.readlines()   #with k scope k bahir print krwaenge tu readlines lgega 
    
for line in contents:#with k scope k bahir for in ka loop chala k contents print krwa rhe hain
    print(line)

123

456

789







In [11]:
filePath = 'untitled.txt'

with open(filePath) as practiceFile:
    contents = practiceFile.readlines()   #with k scope k bahir print krwaenge tu readlines lgega 
    
for line in contents:#with k scope k bahir for in ka loop chala k contents print krwa rhe hain
    print(line.rstrip())

123
456
789




In [13]:
#Printing on same line
filePath = 'untitled.txt'

with open(filePath) as practiceFile:
    contents = practiceFile.readlines()
    
oneline = "" #empty variable

for line in contents:
    oneline += line.rstrip()
    
print(oneline)

123456789


In [15]:
filePath = 'untitled.txt'

with open(filePath) as practiceFile:
    contents = practiceFile.readlines()
    
oneline = "" #empty variable

for line in contents:
    oneline += line.rstrip()
    
print(oneline[:6] + " still continue")   #slicing #slicing mei 1 minus tk print huta ha
print(len(oneline))  #slicing krne se length pe farq nhi para

123456 still continue
9


In [19]:
#Writing on file
filepath= 'untitled.txt'

with open(filepath, "w") as practicefile: # W is ensuring k ye write ka operation ha # read k lye r isi lye nhi likhte kyu k by default with ka method read ko support krrha huta ha
    practicefile.write("000 \n")
    practicefile.write("111")

    

In [20]:
# write puranay contents ko remove krdeta ha
#append puranay aur naye dono contents ko secure rkhta ha

In [22]:
filepath= 'untitled.txt'

with open(filepath, "a") as practicefile:  
    practicefile.write("\n 222 \n")
    practicefile.write("111")

In [23]:
# 5/0 pr python zero division error deta ha
# They are called exceptions
# Controlling the exceptions with may appear

firstnum = 5
secondnum = 0

"""for this purpose we use try and catch block. try k andar ek block of code ko try krte ho aur catch
mei usse anay walay error ko handle krte hou, but in python there are try and except blocks."""

try:
    answer = firstnum / secondnum
    
except ZeroDivisionError:
    print("This operation cannot be performed")
    
else:
    print(answer)
    

This operation cannot be performed


In [24]:
firstnum = 5
secondnum = 3

try:
    answer = firstnum / secondnum
    
except ZeroDivisionError:
    print("This operation cannot be performed")
    
else:
    print(answer)
    

1.6666666666666667


In [26]:
try:
    with open("untitled3.txt") as practicefile:
        contents = practicefile.read()

except FileNotFoundError:
    print("Your file path is incorrect!")
    
else:
    print(contents)

Your file path is incorrect!


In [35]:
"""CSV (Comma Separated Values)
Excel files are CSV files"""
#reading from CSV files 
# MODULES

import csv #ksi b module ko utilize krwane k lye import krwana prta ha

# csv file ka data read krwana ha tou aapko csv.reader() likhna prta ha
with open("Desktop/Book1.csv") as practicefile:
    contents = csv.reader(practicefile)
    for line in contents:
        print(line)
    
#for in loop initialize huga jo csv file se data la k display krega

['Name', 'Dob', 'Gender']
['marium', '2-Oct', 'female']
['asad', '26-Nov', 'male']
['hamza', '26-Nov', 'male']


In [43]:
#Built-in Modules of Python
import math

print(math.pi)

3.141592653589793


In [37]:
import math as mymath

print(mymath.pi)

3.141592653589793


In [39]:
# Module ki kch particular functionality access krne k lyee
from math import pi
print(pi)

3.141592653589793


In [40]:
#Floor 5.3 ko 5 krdega aur ceil 5.3 ko 6 krdega

In [41]:
from math import *
print(pi)

3.141592653589793


In [47]:
import math
a = math.ceil(5.3)
b = math.floor(5.3)
print(a)
print(b)

6
5


In [51]:
import import_ipynb

import Class9b

Class9b.add(5,4)

#Command to run in Terminal (to import other .ipnyb files): pip install import_ipynb


ModuleNotFoundError: No module named 'import_ipynb'

In [ ]:
# 2 packages numpy and pandas : fundamental and imp packages of python
# Use in linear algebra, numerical computational etc
# numpy provides functionality of multi-dimensional array

In [58]:
import numpy as np

data = np.random.randn(2,3) #it will generatre random no # 2,3 mei 2 means 2 arrays and 3 means each array mei 3 random nos chahye
print(data, '\n')

print(data + data, '\n')

print(data * 10, '\n')

print(data.shape, '\n') # it tells no of arrays and no of elements in each array

print(data.dtype, '\n')

print(data.ndim, '\n')

[[ 1.2670611  -0.09695343  1.65540422]
 [-0.75979333  0.12790241  1.96437267]] 

[[ 2.5341222  -0.19390685  3.31080844]
 [-1.51958666  0.25580482  3.92874535]] 

[[12.67061099 -0.96953426 16.55404222]
 [-7.59793332  1.27902412 19.64372673]] 

(2, 3) 

float64 

2 



In [65]:
print(np.zeros(10), '\n') 
print(np.zeros((3,6)), '\n') 
print(np.zeros((2,3,6)), '\n') 

print("Empty",np.empty((3,6)))   #empty mostly gives 0 but can also give you garbage value.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

Empty [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [68]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.astype(np.float64))

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [79]:
arr = np.array([4,2,6,8], dtype = 'int64')
print(arr * 2, '\n')
print(arr * arr, '\n')
print(arr / 2, '\n')
print(arr ** 2, '\n')
print(np.sqrt(arr), '\n')
print(np.exp(arr), '\n')
print(np.mean(arr), '\n')
print(np.sum(arr), '\n')
print(np.cumsum(arr), '\n')
print(np.sort(arr), '\n')

arr2= np.array([0,1,3,5])

print(arr > arr2)


[ 8  4 12 16] 

[16  4 36 64] 

[2. 1. 3. 4.] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

20 

[ 4  6 12 20] 

[2 4 6 8] 

[ True  True  True  True]


In [82]:
arr = np.arange(10)
print(arr)

#slicing
arr2 = arr[5:8]
print(arr2)

arr[:3] = 0 
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [92]:
namesArr = np.array(["Marium","Asad","Hamza", "Marium", "Hina"])
numArr= np.random.randn(5,3)

print(numArr, '\n')
print(namesArr, '\n')
print(namesArr == "Marium",'\n')
print(numArr[namesArr == "Marium"],'\n')
print(numArr[~(namesArr == "Marium")],'\n')

print(np.unique(namesArr)) #sort b krdya aur multiple elements ko neglect krdya


[[-0.07726611 -0.86355047 -0.77586264]
 [-0.55028411  0.50250893  0.55080874]
 [ 1.44978252 -0.51963471  0.36459646]
 [-0.69278225 -0.98818042  1.56027081]
 [ 0.11752643  0.02621061 -0.95809351]] 

['Marium' 'Asad' 'Hamza' 'Marium' 'Hina'] 

[ True False False  True False] 

[[-0.07726611 -0.86355047 -0.77586264]
 [-0.69278225 -0.98818042  1.56027081]] 

[[-0.55028411  0.50250893  0.55080874]
 [ 1.44978252 -0.51963471  0.36459646]
 [ 0.11752643  0.02621061 -0.95809351]] 

['Asad' 'Hamza' 'Hina' 'Marium']


In [95]:
arr = np.random.randn(4)
print(arr,'\n')

arr2 = np.random.randn(4)
print(arr2,'\n')

print(np.maximum(arr,arr2)) #dono arrays k max elements ko ek array mei merge krke new array bnadi
print('\n')
print(np.minimum(arr,arr2))

[-1.17396264  0.41905429  1.15879731  0.29555082] 

[-1.96250237 -1.8029833  -0.61017547  1.23281313] 

[-1.17396264  0.41905429  1.15879731  1.23281313]


[-1.96250237 -1.8029833  -0.61017547  0.29555082]
